# use vi mode
setw -g mode-keys vi
set -g status-keys vi

# true colors
set-option -sa terminal-features ',xterm-256color:RGB'

# change prefix to backtick
unbind C-b
set-option -g prefix `
bind ` send-prefix
