# use vi mode
setw -g mode-keys vi
set -g status-keys vi

# Remove esc delay.
set -sg escape-time 0

# true colors
set-option -sa terminal-features ',xterm-256color:RGB'

# change prefix to backtick
unbind C-b
set-option -g prefix `
bind ` send-prefix

# start with window 1 (instead of 0)
set -g base-index 1

# start with pane 1
set -g pane-base-index 1

# pane splitting
unbind %
bind h split-window -v
unbind '"'
bind v split-window -h

# vim style commands
bind : command-prompt

# source config file
bind r source-file ~/.config/tmux/tmux.conf \; display-message "█▓░ reloaded"

# status line
set -g status-justify left
set -g status-style "bg=terminal,fg=color10"
set -g status-interval 2

# Disable both audible and visual bells
set -g bell-action none
